### ISSUE TITLE
Add 'serverless' support

### ISSUE THREAD

**Issue by jaguililla** [hexagontk/hexagon#405]
Add 'serverless' by using a "fake" server adapter (like the Servlets one) that takes a request from command line arguments.

Check this snippet to set up development environment: https://gist.github.com/crypticmind/c75db15fd774fe8f53282c3ccbe3d7ad and https://hashnode.localstack.cloud/creating-aws-lambda-function-urls-with-localstack

* https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event
* https://cloud.google.com/functions/docs/writing/write-http-functions#http-example-java
* https://github.com/apache/openwhisk-runtime-java
* https://github.com/serverless/examples

**Comment by hrada777** [comment]
### ``
